### ISSUE TITLE
Updating issues

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [Phaiax/gtk-rs-state#1]
I forked this repo (thanks! it solved my gtk-rs multi-threading issues) (https://github.com/andrewdavidmackenzie/gtk-rs-state) and did some simple work to update to 2018 Edition.

I wanted to update to gtk-rs 0.8.0 but ran into issues in gtk/glib well beyond my knowledge.

Current `Cargo.toml` is:
```toml
[package]
name = "gtk-fnonce-on-eventloop"
version = "0.2.1"
authors = ["Phaiax <phaiax-git@invisibletower.de>", "Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "Allows modifing gtk-rs widgets from other threads."
repository = "https://github.com/andrewdavidmackenzie/gtk-rs-state"
license = "MIT"
categories = ["gui"]
edition = "2018"

[dependencies]
lazy_static = "1"
glib = "0.8.2"

[dependencies.gtk]
version = "0.8.0"
features = ["v3_16"]
```

But building fails, as Gtk seems to have made breaking changes with `Continue`

```
Compiling gtk-fnonce-on-eventloop v0.2.1 (/Users/andrew/workspace/gtk-rs-state)
error[E0432]: unresolved import `gtk::Continue`
  --> src/lib.rs:12:13
   |
12 |     pub use gtk::Continue;
   |             ^^^^^^^^^^^^^ no `Continue` in the root
```

I wondered if you had any ideas and if you're interested in keeping up-to-date and would like any PRs in that direction?

thanks!
